In [1]:
pwd

'C:\\Users\\user'

In [2]:
cd C:/Users/user/OneDrive/Desktop/

C:\Users\user\OneDrive\Desktop


In [3]:
import numpy as np

In [4]:
import keras

Using TensorFlow backend.


In [5]:
from keras.preprocessing.text import Tokenizer
from keras.preprocessing.sequence import pad_sequences
from keras.models import Sequential
from keras.layers import Embedding , LSTM , Dense , Dropout

In [6]:
# reading data

with open('reviews.txt') as f:
    reviews = f.read()
    
with open('labels.txt') as f:
    labels = f.read()

In [7]:

print(reviews[:1000])
print()
print(labels[:20])


bromwell high is a cartoon comedy . it ran at the same time as some other programs about school life  such as  teachers  . my   years in the teaching profession lead me to believe that bromwell high  s satire is much closer to reality than is  teachers  . the scramble to survive financially  the insightful students who can see right through their pathetic teachers  pomp  the pettiness of the whole situation  all remind me of the schools i knew and their students . when i saw the episode in which a student repeatedly tried to burn down the school  i immediately recalled . . . . . . . . . at . . . . . . . . . . high . a classic line inspector i  m here to sack one of your teachers . student welcome to bromwell high . i expect that many adults of my age think that bromwell high is far fetched . what a pity that it isn  t   
story of a man who has unnatural feelings for a pig . starts out with a opening scene that is a terrific example of absurd comedy . a formal orchestra audience is turn

# Data pre-processing

In [8]:
# removing punctuation
from string import punctuation

reviews = reviews.lower()
all_text = ''.join([i for i in reviews if i not in punctuation])

# seperate all review
reviews_split = all_text.split('\n')

all_text = ''.join(reviews_split)

words = all_text.split()

In [9]:
print(reviews_split[0:2])

print(len(reviews_split))

['bromwell high is a cartoon comedy  it ran at the same time as some other programs about school life  such as  teachers   my   years in the teaching profession lead me to believe that bromwell high  s satire is much closer to reality than is  teachers   the scramble to survive financially  the insightful students who can see right through their pathetic teachers  pomp  the pettiness of the whole situation  all remind me of the schools i knew and their students  when i saw the episode in which a student repeatedly tried to burn down the school  i immediately recalled          at           high  a classic line inspector i  m here to sack one of your teachers  student welcome to bromwell high  i expect that many adults of my age think that bromwell high is far fetched  what a pity that it isn  t   ', 'story of a man who has unnatural feelings for a pig  starts out with a opening scene that is a terrific example of absurd comedy  a formal orchestra audience is turned into an insane  viole

In [10]:
words[:10]

['bromwell', 'high', 'is', 'a', 'cartoon', 'comedy', 'it', 'ran', 'at', 'the']

### Encoading the word

In [11]:
from collections import Counter

## Build a dictionary that maps words to integers
counts = Counter(words)  # this will count the words how many time they are occured   OR unique word

vocab = sorted(counts, key=counts.get, reverse=True)
vocab_to_int = {word: ii for ii, word in enumerate(vocab, 1)}

In [12]:
vocab_to_int  # this indicates most occured words 

{'the': 1,
 'and': 2,
 'a': 3,
 'of': 4,
 'to': 5,
 'is': 6,
 'br': 7,
 'it': 8,
 'in': 9,
 'i': 10,
 'this': 11,
 'that': 12,
 's': 13,
 'was': 14,
 'as': 15,
 'for': 16,
 'with': 17,
 'movie': 18,
 'but': 19,
 'film': 20,
 'you': 21,
 'on': 22,
 't': 23,
 'not': 24,
 'he': 25,
 'are': 26,
 'his': 27,
 'have': 28,
 'be': 29,
 'one': 30,
 'all': 31,
 'at': 32,
 'they': 33,
 'by': 34,
 'an': 35,
 'who': 36,
 'so': 37,
 'from': 38,
 'like': 39,
 'there': 40,
 'her': 41,
 'or': 42,
 'just': 43,
 'about': 44,
 'out': 45,
 'if': 46,
 'has': 47,
 'what': 48,
 'some': 49,
 'good': 50,
 'can': 51,
 'more': 52,
 'she': 53,
 'when': 54,
 'very': 55,
 'up': 56,
 'time': 57,
 'no': 58,
 'even': 59,
 'my': 60,
 'would': 61,
 'which': 62,
 'story': 63,
 'only': 64,
 'really': 65,
 'see': 66,
 'their': 67,
 'had': 68,
 'we': 69,
 'were': 70,
 'me': 71,
 'well': 72,
 'than': 73,
 'much': 74,
 'get': 75,
 'bad': 76,
 'been': 77,
 'people': 78,
 'will': 79,
 'do': 80,
 'other': 81,
 'also': 82,
 'into':

In [13]:
len(vocab_to_int)

74072

In [14]:
# now time to convert each reviews into tokens
review_int = []
for review in reviews_split:
    review_int.append([vocab_to_int[word] for word in review.split()])

In [15]:
print('Unique words: ', len((vocab_to_int)))  # should ~ 74000+
print()

# print tokens in first review
print('Tokenized review: \n', review_int[:1])
print()

print('Actual review : \n' , reviews_split[:1])

Unique words:  74072

Tokenized review: 
 [[21025, 308, 6, 3, 1050, 207, 8, 2138, 32, 1, 171, 57, 15, 49, 81, 5785, 44, 382, 110, 140, 15, 5194, 60, 154, 9, 1, 4975, 5852, 475, 71, 5, 260, 12, 21025, 308, 13, 1978, 6, 74, 2395, 5, 613, 73, 6, 5194, 1, 24103, 5, 1983, 10166, 1, 5786, 1499, 36, 51, 66, 204, 145, 67, 1199, 5194, 19869, 1, 37442, 4, 1, 221, 883, 31, 2988, 71, 4, 1, 5787, 10, 686, 2, 67, 1499, 54, 10, 216, 1, 383, 9, 62, 3, 1406, 3686, 783, 5, 3483, 180, 1, 382, 10, 1212, 13583, 32, 308, 3, 349, 341, 2913, 10, 143, 127, 5, 7690, 30, 4, 129, 5194, 1406, 2326, 5, 21025, 308, 10, 528, 12, 109, 1448, 4, 60, 543, 102, 12, 21025, 308, 6, 227, 4146, 48, 3, 2211, 12, 8, 215, 23]]

Actual review : 
 ['bromwell high is a cartoon comedy  it ran at the same time as some other programs about school life  such as  teachers   my   years in the teaching profession lead me to believe that bromwell high  s satire is much closer to reality than is  teachers   the scramble to survive financial

In [16]:
len(review_int)

25001

### Encoading labels

In [17]:
label = labels.split('\n')
encoded_label = np.array([1 if lab == 'positive' else 0 for lab in label])

In [18]:
print(len(encoded_label))
encoded_label[:10]

25001


array([1, 0, 1, 0, 1, 0, 1, 0, 1, 0])

In [19]:
# removieng review of 0 length

length = Counter([len(x) for x in review_int])

print("Zero-length reviews: {}".format(length[0]))
print("Maximum review length: {}".format(max(length)))

Zero-length reviews: 1
Maximum review length: 2514


In [20]:
## remove any reviews/labels with zero length from the reviews_ints list.

# get indices of any reviews with length 0
non_zero_idx = [ii for ii, review in enumerate(review_int) if len(review) != 0]

# remove 0-length reviews and their labels
reviews_ints = [review_int[ii] for ii in non_zero_idx]
encoded_labels = np.array([encoded_label[ii] for ii in non_zero_idx])

print('Number of reviews after removing outliers: ', len(reviews_ints))

Number of reviews after removing outliers:  25000


## Padding sequences

In [21]:
# we can only give fixed length data to our model but here data is not fixed length so we need to fix them.
# padding----->>> it is a process of adding 0 to our data token to increase lenght of our data to a specific limit
# truncating----->>> it is a process of removing some tokens from our data to reduce data to a specific length

In [22]:
# max length in our data is 2514.
seq_length = 200  # all data will be of this length

In [23]:
def pad_func(reviews_ints,seq_length):
    
    for x ,i in enumerate(reviews_ints):
        
        if len(i) > seq_length:
            reviews_ints[x] = i[:seq_length]
        if len(i) < seq_length:
            y = seq_length - len(i)
            for l in range(y):
                i.insert(0,0)
            reviews_ints[x] = i
        
    return reviews_ints

In [24]:
features = pad_func(reviews_ints,seq_length)

In [25]:
features = np.asarray(features)

In [26]:
len(features)

25000

In [27]:
print(features[:30,:10])

[[    0     0     0     0     0     0     0     0     0     0]
 [    0     0     0     0     0     0     0     0     0     0]
 [22382    42 46418    15   706 17139  3389    47    77    35]
 [ 4505   505    15     3  3342   162  8312  1652     6  4819]
 [    0     0     0     0     0     0     0     0     0     0]
 [    0     0     0     0     0     0     0     0     0     0]
 [    0     0     0     0     0     0     0     0     0     0]
 [    0     0     0     0     0     0     0     0     0     0]
 [    0     0     0     0     0     0     0     0     0     0]
 [   54    10    14   116    60   798   552    71   364     5]
 [    0     0     0     0     0     0     0     0     0     0]
 [    0     0     0     0     0     0     0     0     0     0]
 [    0     0     0     0     0     0     0     0     0     0]
 [    1   330   578    34     3   162   748  2731     9   325]
 [    9    11 10171  5305  1946   689   444    22   280   673]
 [    0     0     0     0     0     0     0     0     0

In [28]:
features.shape

(25000, 200)

## Training, Validation, Test

In [29]:
from sklearn.model_selection import train_test_split

In [30]:
x_train, X_test, y_train, y_test = train_test_split(features,encoded_labels,test_size=0.2)

In [31]:
vocub_size = len(vocab_to_int)+1
embedding_size = 300

input_words = 200

In [32]:
model = Sequential()

In [33]:
model.add(Embedding(input_dim=vocub_size , output_dim=embedding_size , input_length=seq_length))
model.add(LSTM(units=200,dropout=0.3,return_sequences=True))
model.add(LSTM(100))
model.add(Dropout(0.25))
model.add(Dense(1,activation='sigmoid'))

Instructions for updating:
Colocations handled automatically by placer.
Instructions for updating:
Please use `rate` instead of `keep_prob`. Rate should be set to `rate = 1 - keep_prob`.


In [34]:
model.summary()

_________________________________________________________________
Layer (type)                 Output Shape              Param #   
embedding_1 (Embedding)      (None, 200, 300)          22221900  
_________________________________________________________________
lstm_1 (LSTM)                (None, 200, 200)          400800    
_________________________________________________________________
lstm_2 (LSTM)                (None, 100)               120400    
_________________________________________________________________
dropout_1 (Dropout)          (None, 100)               0         
_________________________________________________________________
dense_1 (Dense)              (None, 1)                 101       
Total params: 22,743,201
Trainable params: 22,743,201
Non-trainable params: 0
_________________________________________________________________


In [35]:
model.compile(loss='binary_crossentropy', optimizer='adam', metrics=['accuracy'])

In [38]:
model.fit(x_train,y_train,batch_size=1000,validation_split=0.05,epochs=3)

Train on 19000 samples, validate on 1000 samples
Epoch 1/3
19000/19000 [==============================] - 352s 19ms/step - loss: 0.6495 - acc: 0.6467 - val_loss: 0.5607 - val_acc: 0.7430
Epoch 2/3
19000/19000 [==============================] - 398s 21ms/step - loss: 0.4187 - acc: 0.8210 - val_loss: 0.4472 - val_acc: 0.7940
Epoch 3/3
19000/19000 [==============================] - 469s 25ms/step - loss: 0.2609 - acc: 0.9036 - val_loss: 0.3955 - val_acc: 0.8280


### performance on test

In [39]:
model.evaluate(X_test,y_test)

5000/5000 [==============================] - 57s 11ms/step


[0.37576404457092283, 0.8412]

In [85]:
X_test.shape

(5000, 200)

Prediction

In [41]:
pred = model.predict(X_test)

In [43]:
from sklearn.metrics import accuracy_score

In [44]:
pred.shape

(5000, 1)

In [51]:
y_test.shape

(5000,)

In [57]:
# making pred either 0 or 1
y_pred =[]
for i in pred:
    y_pred.append(round(i[0]))

In [58]:
y_test[890]

1

In [59]:
y_pred[890]

1.0

In [60]:
accuracy_score(y_test,y_pred)

0.8412

# Working on new data

In [89]:
text1 = "This movie is fantastic! I really like it because it is so good!"
text2 = "Good movie!"
text3 = "Maybe I like this movie."
text4 = "Meh ..."
text5 = "If I were a drunk teenager then this movie might be good."
text6 = "Bad movie!"
text7 = "Not a good movie!"
text8 = "This movie really sucks! Can I get my money back please?"
texts = [text1, text2, text3, text4, text5, text6, text7, text8]

In [102]:
def tokenize_review(test_review):
    test_review = test_review.lower() # lowercase
    # get rid of punctuation
    test_text = ''.join([c for c in test_review if c not in punctuation])

    # splitting by spaces
    test_words = test_text.split()

    # tokens
    test_ints = []
    test_ints.append([vocab_to_int[word] for word in test_words])

    return test_ints

In [103]:
text_int = []
for text in texts:
    text_int.append(tokenize_review(text))

In [104]:
len(text_int)

8

In [111]:
text_ints = []
for i in text_int:
    text_ints.append(i[0])
text_ints

[[11, 18, 6, 759, 10, 65, 39, 8, 86, 8, 6, 37, 50],
 [50, 18],
 [277, 10, 39, 11, 18],
 [23472],
 [46, 10, 70, 3, 1793, 2277, 93, 11, 18, 233, 29, 50],
 [76, 18],
 [24, 3, 50, 18],
 [11, 18, 65, 1853, 51, 10, 75, 60, 273, 144, 579]]

In [112]:
test = pad_func(text_ints,seq_length)

In [113]:
test = np.asarray(test)
test.shape

(8, 200)

In [114]:
# making predction

In [121]:
pred = model.predict(test)

pred

array([[0.48941648],
       [0.05284208],
       [0.05284262],
       [0.04335314],
       [0.03752649],
       [0.03189379],
       [0.05792692],
       [0.06281474]], dtype=float32)